learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path
from .import views

app_name = 'learning_logs'

urlpatterns = [
#     Home page
    path('', views.index, name = 'index'),

#     Page that shows all topics
    path('topics/', views.topics, name = 'topics'),

#     Detail page for a single topic
    path('topic/<int:topic_id>/', views.topic, name = 'topic'),

#     Page for adding a new topic
    path('new_topic/', views.new_topic, name = 'new_topic'),

#     Page for adding a new entry
    path('<int:topic_id>/new_entry/', views.new_entry, name = 'new_entry'),

#     Page for editing a topic
    path('<int:topic_id>/edit/', views.edit_topic, name = 'edit_topic'),

#     Page for editing an entry
    path('<int:topic_id>/<int:entry_id>/edit/', views.edit_entry, name = 'edit_entry'),

#     Page for deleting a topic
    path('<int:topic_id>/delete/', views.delete_topic, name = 'delete_topic'),

#     Page for deleting an entry
    path('<int:topic_id>/<int:entry_id>/delete/', views.delete_entry, name = 'delete_entry'),
]

learning_log/users/urls.py
""""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),

#     Registration page
    path('register/', views.register, name = 'register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    # Override Django reference to refer to multiple as "Entries" not "Entrys"
    class Meta:
        verbose_name_plural = 'Entries'

    def __str__(self):
        """Return a string representation of the model"""
        if(len(self.text) > 50):
            return f"{self.text[:50]}..."
        return f"{self.text}"

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        # Overrides Django default form size, widening entry field so user can see
        # their message better
        widgets = {'text': forms.Textarea(attrs = {'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    topic = Topic.objects.get(id = topic_id)

    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TopicForm()
    else:
        # POST data submitted; process data
        form = TopicForm(data = request.POST)
        if form.is_valid():
            new_topic = form.save(commit = False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # Display a blank of invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""
    topic = Topic.objects.get(id = topic_id)

    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submittted; create a blank form
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_topic(request, topic_id):
    """Edit a topic"""
    topic = Topic.objects.get(id = topic_id)

    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TopicForm(instance = topic)
    else:
        # POST data submitted; process data
        form = TopicForm(instance = topic, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)

@login_required
def edit_entry(request, topic_id, entry_id):
    """Edit an entry"""
    topic = Topic.objects.get(id = topic_id)
    entry = Entry.objects.get(id = entry_id)

    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = EntryForm(instance = entry)
    else:
        # POST data submitted; process data
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
    # Display a blank or invalid form
    context = {'topic': topic, 'entry': entry, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_topic(request, topic_id):
    """Delete a topic"""
    topic = Topic.objects.get(id = topic_id)

    if topic.owner != request.user:
        raise Http404

    topic.delete()
    return redirect('learning_logs:topics')

@login_required
def delete_entry(request, topic_id, entry_id):
    """Delete an entry"""
    topic = Topic.objects.get(id = topic_id)
    entry = Entry.objects.get(id = entry_id)

    if topic.owner != request.user:
        raise Http404

    entry.delete()
    return redirect('learning_logs:topic', topic_id = topic_id)

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display a blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page
            login(request, new_user)
            return redirect('learning_logs:index')
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap5 %}

<!doctype html>
<html lang = "en">
<head>
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1
        shrink-to-fit=no">
    <title>
        Learning Log
    </title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>

    <nav class = "navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class = "container-fluid">

        <!-- Navbar Brand -->
        <a class = "navbar-brand" href = "{% url 'learning_logs:index' %}">
            Learning Log
        </a>

        <!-- Navbar Toggler Button for Small Screens -->
        <button class = "navbar-toggler" type = "button" data-bs-toggle = "collapse"
            data-bs-target = "#navbarCollapse" aria-controls = "navbarCollapse"
            aria-expanded = "false" aria-label = "Toggle-navigation">
            <span class = "navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Collapsible Section -->
        <div class = "collapse navbar-collapse" id = "navbarCollapse">

            <!-- Left Side: Topics -->
            {% if user.is_authenticated %}
                <ul class = "navbar-nav me-auto">
                    <li class = "nav-item">
                        <a class = "nav-link" href = "{% url 'learning_logs:topics' %}">
                            Topics
                        </a>
                    </li>
                </ul>

            <!-- Centered Username (Only shown if logged in) -->
                <spann class = "navbar-text mx-auto">
                    {{ user.username }}
                </spann>

            <!-- Right Side: Logout -->
                <ul class = "navbar-nav ms-auto">
                    <li class = "nav-item">
                        <form action = "{% url 'users:logout' %}" method = "post">
                            {% csrf_token %}
                            <button type = "submit" class = "nav-link btn btn-link">
                                Log Out
                            </button>
                        </form>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>

    <main role = "main" class = "container">
        <div class = "pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h1>
        Edit Entry
    </h1>
{% endblock page_header %}

{% block content %}

    <form method = "post" action = "{% url 'learning_logs:edit_entry' topic.id entry.id %}" class = "form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name = "submit" class = "btn btn-primary">
                Save Edit
            </button>
        {% endbuttons %}
    </form>

    <a href = "{% url 'learning_logs:topic' topic.id %}"
       class = "btn btn-secondary">
        Cancel
    </a>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h1>
        Edit Topic
    </h1>
{% endblock page_header %}

{% block content %}

    <form method = "post" action = "{% url 'learning_logs:edit_topic' topic.id %}" class = "form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name = "submit" class = "btn btn-primary">
                Save Edit
            </button>
        {% endbuttons %}
    </form>

    <a href = "{% url 'learning_logs:topics' %}"
       class = "btn btn-secondary">
        Cancel
    </a>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <div class = "jumbotron">
        <h1 class = "display-3">
            Track your learning
        </h1>

        <p class = "lead">
            Make your own Learning Log, and keep a list of the topics
            you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.
        </p>

        {% if not user.is_authenticated %}
            <p>
                <a class = "btn btn-lg btn-primary" href = "{% url 'users:login' %}"
                   role = "button">
                    Log In
                </a>
            </p>

            <a class = "btn btn-lg btn-primary" href = "{% url 'users:register' %}"
               role = "button">
                Register
            </a>
        {% endif %}
    </div>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h1>
        {{ topic }}
    </h1>
    <h5>
        Add Entry
    </h5>
{% endblock page_header %}

{% block content %}

    <form method = "post" action = "{% url 'learning_logs:new_entry' topic.id %}" class = "form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name = "submit" class = "btn btn-primary">
                Save Entry
            </button>
        {% endbuttons %}
    </form>

    <a href = "{% url 'learning_logs:topic' topic.id %}"
       class = "btn btn-secondary">
        Cancel
    </a>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h1>
        Add Topic
    </h1>
{% endblock page_header %}

{% block content %}
    <form method = "post" action = "{% url 'learning_logs:new_topic' %}" class = "form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name = "submit" class = "btn btn-primary">
                Save Topic
            </button>
        {% endbuttons %}
    </form>

    <a href = "{% url 'learning_logs:topics' %}"
       class = "btn btn-secondary">
        Cancel
    </a>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>
        {{ topic }}
    </h1>
{% endblock page_header %}

{% block content %}

    <p>
        <a href = "{% url 'learning_logs:new_entry' topic.id %}"
        class = "btn btn-primary">
            Add Entry
        </a>
    </p>

    {% for entry in entries %}
        <div class = "card mb-3">
            <h4 class = "chard-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
            </h4>

            <div class = "card-body">
                {{ entry.text|linebreaks }}
            </div>

            <p><a href = "{% url 'learning_logs:edit_entry' topic.id entry.id %}"
                class = "btn btn-secondary">
                    Edit Entry
            </a></p>

            <a href = "{% url 'learning_logs:delete_entry' topic.id entry.id %}">
                {% csrf_token %}
                <button type = "submit" class = "btn btn-danger">
                    Delete Entry
                </button>
            </a>

        </div>
    {% empty %}
        <p>
            There are no entries for this topic yet
        </p>
    {% endfor %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h1>
        Topics
    </h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h3>
                <p><a href = "{% url 'learning_logs:topic' topic.id %}">
                    {{ topic }}
                </a></p>

                <p><a href = "{% url 'learning_logs:edit_topic' topic.id %}"
                   class = "btn btn-secondary">
                        Edit Topic
                </a></p>

                <a href = "{% url 'learning_logs:delete_topic' topic.id %}">
                    {% csrf_token %}
                    <button type = "submit" class = "btn btn-danger">
                        Delete Topic
                    </button>
                </a>

            </h3></li>
        {% empty %}
            <li><h3>
                No topics have been added yet
            </h3></li>
        {% endfor %}
    </ul>

    <h3>
        <a href = "{% url 'learning_logs:new_topic' %}"
            class = "btn btn-primary">
                Add Topic
        </a>
    </h3>

{% endblock content %}